import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { useState } from 'react'
import { api, setStoredAuth } from '../lib-auth.ts'
export const Route = createFileRoute('/login')({ component: LoginPage })
function LoginPage() {
  const navigate = useNavigate(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(''); setLoading(true); try { const data = await api<{token:string; user:any}>('/api/login',{method:'POST', body: JSON.stringify({ email, password })}); setStoredAuth(data.token,data.user); navigate({to:'/dashboard'}) } catch(err){ setError(err instanceof Error ? err.message : 'Error') } finally { setLoading(false) } }
  return <div className="min-h-screen bg-slate-50 px-4 py-16"><div className="mx-auto max-w-md rounded-[2rem] border border-slate-200 bg-white p-8 shadow-soft"><p className="text-center text-sm font-bold uppercase tracking-[0.2em] text-violet-600">ClickWeb</p><h1 className="mt-3 text-center text-4xl font-black">Iniciar sesión</h1><p className="mt-3 text-center text-slate-500">Gestiona tus webs, tus planes y tus cambios desde una sola cuenta.</p><form onSubmit={submit} className="mt-8 space-y-4"><input value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="Email" className="w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-violet-400" /><input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="Contraseña" className="w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-violet-400" />{error && <div className="rounded-2xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<button disabled={loading} className="w-full rounded-2xl bg-gradient-to-r from-violet-600 to-indigo-600 px-4 py-3 font-bold text-white disabled:opacity-50">{loading ? 'Iniciando sesión...' : 'Iniciar sesión'}</button></form><p className="mt-6 text-center text-sm text-slate-500">¿No tienes cuenta? <Link to="/register" className="font-bold text-violet-600">Crear cuenta</Link></p></div></div>
}
